<?php

namespace Tests\Unit;

use App\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;
use UsersTableSeeder;

class UserTest extends TestCase
{
    use DatabaseMigrations;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed(UsersTableSeeder::class);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testUsersController()
    {
        $response = $this->get('/api/users');
        $response->assertStatus(200);

        //should have data key
        $response->assertJson(['data' => true]);
    }

    public function testUsersDatabase()
    {
        $users = User::all();

        $this->assertGreaterThanOrEqual(UsersTableSeeder::USERS_NUMBER, count($users));
    }

}
